/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWalletTopupRouteImport } from './routes/api/wallet-topup'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as ApiLivekitTokenRouteImport } from './routes/api/livekit-token'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletTopupRoute = ApiWalletTopupRouteImport.update({
  id: '/api/wallet-topup',
  path: '/api/wallet-topup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLivekitTokenRoute = ApiLivekitTokenRouteImport.update({
  id: '/api/livekit-token',
  path: '/api/livekit-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/livekit-token': typeof ApiLivekitTokenRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/wallet-topup': typeof ApiWalletTopupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/livekit-token': typeof ApiLivekitTokenRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/wallet-topup': typeof ApiWalletTopupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/livekit-token': typeof ApiLivekitTokenRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/wallet-topup': typeof ApiWalletTopupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/api/checkout'
    | '/api/livekit-token'
    | '/api/stripe-webhook'
    | '/api/wallet-topup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/api/checkout'
    | '/api/livekit-token'
    | '/api/stripe-webhook'
    | '/api/wallet-topup'
  id:
    | '__root__'
    | '/'
    | '/reset-password'
    | '/api/checkout'
    | '/api/livekit-token'
    | '/api/stripe-webhook'
    | '/api/wallet-topup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiLivekitTokenRoute: typeof ApiLivekitTokenRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiWalletTopupRoute: typeof ApiWalletTopupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet-topup': {
      id: '/api/wallet-topup'
      path: '/api/wallet-topup'
      fullPath: '/api/wallet-topup'
      preLoaderRoute: typeof ApiWalletTopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/livekit-token': {
      id: '/api/livekit-token'
      path: '/api/livekit-token'
      fullPath: '/api/livekit-token'
      preLoaderRoute: typeof ApiLivekitTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiLivekitTokenRoute: ApiLivekitTokenRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiWalletTopupRoute: ApiWalletTopupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
