/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWalletTopupRouteImport } from './routes/api/wallet-topup'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as ApiLivekitTokenRouteImport } from './routes/api/livekit-token'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiWalletTopupConfirmRouteImport } from './routes/api/wallet-topup.confirm'
import { Route as ApiCheckoutConfirmRouteImport } from './routes/api/checkout.confirm'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletTopupRoute = ApiWalletTopupRouteImport.update({
  id: '/api/wallet-topup',
  path: '/api/wallet-topup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLivekitTokenRoute = ApiLivekitTokenRouteImport.update({
  id: '/api/livekit-token',
  path: '/api/livekit-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletTopupConfirmRoute = ApiWalletTopupConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => ApiWalletTopupRoute,
} as any)
const ApiCheckoutConfirmRoute = ApiCheckoutConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => ApiCheckoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/api/checkout': typeof ApiCheckoutRouteWithChildren
  '/api/livekit-token': typeof ApiLivekitTokenRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/wallet-topup': typeof ApiWalletTopupRouteWithChildren
  '/api/checkout/confirm': typeof ApiCheckoutConfirmRoute
  '/api/wallet-topup/confirm': typeof ApiWalletTopupConfirmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/api/checkout': typeof ApiCheckoutRouteWithChildren
  '/api/livekit-token': typeof ApiLivekitTokenRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/wallet-topup': typeof ApiWalletTopupRouteWithChildren
  '/api/checkout/confirm': typeof ApiCheckoutConfirmRoute
  '/api/wallet-topup/confirm': typeof ApiWalletTopupConfirmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/api/checkout': typeof ApiCheckoutRouteWithChildren
  '/api/livekit-token': typeof ApiLivekitTokenRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/wallet-topup': typeof ApiWalletTopupRouteWithChildren
  '/api/checkout/confirm': typeof ApiCheckoutConfirmRoute
  '/api/wallet-topup/confirm': typeof ApiWalletTopupConfirmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/api/checkout'
    | '/api/livekit-token'
    | '/api/stripe-webhook'
    | '/api/wallet-topup'
    | '/api/checkout/confirm'
    | '/api/wallet-topup/confirm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/api/checkout'
    | '/api/livekit-token'
    | '/api/stripe-webhook'
    | '/api/wallet-topup'
    | '/api/checkout/confirm'
    | '/api/wallet-topup/confirm'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/api/checkout'
    | '/api/livekit-token'
    | '/api/stripe-webhook'
    | '/api/wallet-topup'
    | '/api/checkout/confirm'
    | '/api/wallet-topup/confirm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiCheckoutRoute: typeof ApiCheckoutRouteWithChildren
  ApiLivekitTokenRoute: typeof ApiLivekitTokenRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiWalletTopupRoute: typeof ApiWalletTopupRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet-topup': {
      id: '/api/wallet-topup'
      path: '/api/wallet-topup'
      fullPath: '/api/wallet-topup'
      preLoaderRoute: typeof ApiWalletTopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/livekit-token': {
      id: '/api/livekit-token'
      path: '/api/livekit-token'
      fullPath: '/api/livekit-token'
      preLoaderRoute: typeof ApiLivekitTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet-topup/confirm': {
      id: '/api/wallet-topup/confirm'
      path: '/confirm'
      fullPath: '/api/wallet-topup/confirm'
      preLoaderRoute: typeof ApiWalletTopupConfirmRouteImport
      parentRoute: typeof ApiWalletTopupRoute
    }
    '/api/checkout/confirm': {
      id: '/api/checkout/confirm'
      path: '/confirm'
      fullPath: '/api/checkout/confirm'
      preLoaderRoute: typeof ApiCheckoutConfirmRouteImport
      parentRoute: typeof ApiCheckoutRoute
    }
  }
}

interface ApiCheckoutRouteChildren {
  ApiCheckoutConfirmRoute: typeof ApiCheckoutConfirmRoute
}

const ApiCheckoutRouteChildren: ApiCheckoutRouteChildren = {
  ApiCheckoutConfirmRoute: ApiCheckoutConfirmRoute,
}

const ApiCheckoutRouteWithChildren = ApiCheckoutRoute._addFileChildren(
  ApiCheckoutRouteChildren,
)

interface ApiWalletTopupRouteChildren {
  ApiWalletTopupConfirmRoute: typeof ApiWalletTopupConfirmRoute
}

const ApiWalletTopupRouteChildren: ApiWalletTopupRouteChildren = {
  ApiWalletTopupConfirmRoute: ApiWalletTopupConfirmRoute,
}

const ApiWalletTopupRouteWithChildren = ApiWalletTopupRoute._addFileChildren(
  ApiWalletTopupRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiCheckoutRoute: ApiCheckoutRouteWithChildren,
  ApiLivekitTokenRoute: ApiLivekitTokenRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiWalletTopupRoute: ApiWalletTopupRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
