// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djwuvxpmvrwfjwjamjno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqd3V2eHBtdnJ3Zmp3amFtam5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYzNTg4NTYsImV4cCI6MjEwMTkzNDg1Nn0.fCIOzg7Sp8K7UE_Tev-jkKjeUtLWYuvy4H_TERqEsG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});